version: '3'
services:
  postgresql:
    image: postgres:latest
    command: postgres -c 'max_connections=100'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: be_nest_education
  redis:
    image: redis:latest
    command: redis-server --requirepass redis_password
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis_password
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
